//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenGate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenGate.AppResource ", typeof(AppResource_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 MŨI.
        /// </summary>
        internal static string FirstDose {
            get {
                return ResourceManager.GetString("FirstDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRCode này vừa mới được scan và chỉ mới tiêm 1 mũi.
        /// </summary>
        internal static string FirstDoseWarning {
            get {
                return ResourceManager.GetString("FirstDoseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRCode này vừa mới được scan và đủ 2 mũi.
        /// </summary>
        internal static string GoodCodeWarning {
            get {
                return ResourceManager.GetString("GoodCodeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mời người tiếp theo.
        /// </summary>
        internal static string NextOne {
            get {
                return ResourceManager.GetString("NextOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin cố định mã QR.
        /// </summary>
        internal static string PleaseKeepImageStable {
            get {
                return ResourceManager.GetString("PleaseKeepImageStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhận QRCode, xin cố định hình ảnh trong 3 giây.
        /// </summary>
        internal static string QrCodeReceived {
            get {
                return ResourceManager.GetString("QrCodeReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang scan chứng nhận cho QRCode này.
        /// </summary>
        internal static string ScanningInformationWarning {
            get {
                return ResourceManager.GetString("ScanningInformationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang scan QRCode mới.
        /// </summary>
        internal static string ScanningNewOneWarning {
            get {
                return ResourceManager.GetString("ScanningNewOneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 MŨI.
        /// </summary>
        internal static string SecondDose {
            get {
                return ResourceManager.GetString("SecondDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu.
        /// </summary>
        internal static string StrStart {
            get {
                return ResourceManager.GetString("StrStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        internal static string StrStop {
            get {
                return ResourceManager.GetString("StrStop", resourceCulture);
            }
        }
    }
}
